development:
  host: "http://dev.kokavo.com"
  uploads_dir: "uploads"
  appoxee:
    campaign_id: 158592
    application_id: 102484

qa:
  host: http://qa.kokavo.com
  uploads_dir: uploads
  appoxee:
    campaign_id: 158592
    application_id: 102484

production:
  host: "http://www.kokavo.com"
  uploads_dir: "uploads"
  appoxee:
    campaign_id: 157105
    application_id: 101608

